export enum IconType {
  apple = 'apple',
  back = 'back',
  bancoDoBrasil = 'bancoDoBrasil',
  bank = 'bank',
  check = 'check',
  chevronRight = 'chevronRight',
  close = 'close',
  error = 'error',
  google = 'google',
  inter = 'inter',
  itau = 'itau',
  moneyPath = 'moneyPath',
  nubank = 'nubank',
  santander = 'santander',
  wallet = 'wallet',
  warning = 'warning',
}
