export enum IconType {
  apple = 'apple',
  back = 'back',
  bancoDoBrasil = 'bancoDoBrasil',
  bank = 'bank',
  check = 'check',
  chevronRight = 'chevronRight',
  close = 'close',
  error = 'error',
  food = 'food',
  games = 'games',
  google = 'google',
  health = 'health',
  help = 'help',
  house = 'house',
  inter = 'inter',
  itau = 'itau',
  moneyPath = 'moneyPath',
  money = 'money',
  nubank = 'nubank',
  santander = 'santander',
  transport = 'transport',
  wallet = 'wallet',
  warning = 'warning',
}
